#! /bin/bash

zip dcemriS4_v3 dcemri3.Rnw dcemri.bib *.png buckley_aif.pdf \
    *compare.pdf boxplots.pdf rawtimes.txt *tensor*.nii.gz *mask* \
    *ktrans.nii.gz *ktrans_map.nii.gz *kep.nii.gz *vp.nii.gz *ve.nii.gz \
    *sse.nii.gz *ktrans_bayes*.nii.gz *spline*.nii.gz jsslogo.jpg \
    *perfusion.nii.gz *perfusion_gdconc.nii.gz

